[package]
name = "dirhash"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.26"
humansize = "2.1.3"
indicatif = "0.17.5"
sha256 = "1.1.4"
walkdir = "2.3.3"
